# Generated by Django 4.1.7 on 2023-06-01 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("client", "0003_alter_customclient_sales_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customclient",
            name="sales_contact",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"usergroup": "Sale"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
