# Generated by Django 4.1.7 on 2023-06-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="create_time",
            field=models.DateField(blank=True, null=True),
        ),
    ]
