# Generated by Django 4.1.7 on 2023-06-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_customuser_create_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="create_time",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
