# Generated by Django 4.1.7 on 2023-06-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_customuser_create_time_alter_customuser_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="usergroupe",
            new_name="usergroup",
        ),
    ]
