# Generated by Django 4.1.7 on 2023-05-18 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                ("amount", models.FloatField()),
                ("payment_due", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("SIGNED", "Contract Signed"),
                            ("ENDED", "Ended"),
                        ],
                        default="OPEN",
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "event_status",
                    models.BooleanField(default=False, verbose_name="Completed"),
                ),
                ("attendees", models.PositiveIntegerField()),
                ("event_date", models.DateTimeField(blank=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "contract",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"status": "OPEN"},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract",
                        to="contracts.contract",
                    ),
                ),
            ],
        ),
    ]
